# version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data_d:/var/lib/mysql

    networks:
      - app_network

  server:
    build:
      context: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 -w 2
    restart: unless-stopped
    
    container_name: server
    # depends_on:
    #   - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network



  celery_worker:
    build: .
    container_name: app_celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app_network


volumes:
  # psql_data:
  redis_data:

networks:
  app_network:
    driver: bridge