# Generated by Django 5.2.5 on 2025-09-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nl_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['id']},
        ),
    ]
